name: Build and deploy Python app to Azure Web App - frugalrockfinancing

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy job

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Run database migrations  
        run: |
          source venv/bin/activate  
          python manage.py migrate
          
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # - name: Run tests
      #   run: |
      #     source venv/bin/activate
      #     pytest
        
      - name: Zip artifact for deployment
        run: |
          source venv/bin/activate  # Ensure activation before zipping
          zip -r release.zip ./* -x venv/\*
          
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'frugalrockfinancing'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4EEAA80A8A574E6AA9B98E963C720BED }}
